function [sumamp,diffamp,phasedelta] = helperSimulateMonopulse(fc_hb100,steerangles)
    % Simulate the monopulse pattern for the ADI phaser.

    % Get the sum pattern
    rxpos = [0;0;0];
    txpos = [0;10;0];
    [sumamp,sumphase] = helperSimulateAntennaSteering(fc_hb100,rxpos,txpos,steerangles);
    
    % The diff pattern is generated by setting the digital weights to
    % [1;-1]
    analogweights = ones(4,2);
    digitalweights = [1;-1];
    [diffamp,diffphase] = helperSimulateAntennaSteering(fc_hb100,rxpos,txpos,steerangles,analogweights,digitalweights);
    phasedelta = sign(wrapTo180(sumphase-diffphase));
end